services:
  postgres:
    container_name: catalog_db
    image: postgres:17.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always

volumes:
  postgres_data:
    driver: local